CREATE DATABASE IF NOT EXISTS ESPELHOMEU
DEFAULT CHARACTER SET UTF8
DEFAULT COLLATE UTF8_GENERAL_CI;

USE ESPELHOMEU;

CREATE TABLE IF NOT EXISTS NIVEL (
    ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(80) NOT NULL
);
CREATE TABLE IF NOT EXISTS LOGIN (
    ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USUARIO VARCHAR(80) NOT NULL UNIQUE,
    SENHA VARCHAR(150) NOT NULL,
    STATUS SET('N', 'S') NOT NULL,
    FK_NIVEL INT(11) NOT NULL,
    FOREIGN KEY (FK_NIVEL) REFERENCES NIVEL(ID)
);

CREATE TABLE IF NOT EXISTS CLIENTE (
    ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(100) NOT NULL,
    NOME VARCHAR(80) NOT NULL,
    CPF INT(11) NOT NULL,
    RG  INT(9) NOT NULL,
    TELEFONE INT(11),
    FK_LOGIN INT(11) NOT NULL,
    FOREIGN KEY (FK_LOGIN) REFERENCES LOGIN(ID)
);

CREATE TABLE IF NOT EXISTS SERVICO (
    ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(80) NOT NULL,
    DESCRICAO TEXT NOT NULL,
    VALOR DECIMAL(9,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS HORARIO (
    ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    HORA TIME,
    FK_SERVICO INT(11) NOT NULL,
    FOREIGN KEY (FK_SERVICO) REFERENCES SERVICO(ID)
);

CREATE TABLE IF NOT EXISTS AGENDAMENTO (
    ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DATA DATE,
    FK_HORARIO INT(11) NOT NULL,
    FK_CLIENTE INT(11) NOT NULL,
    FOREIGN KEY (FK_HORARIO) REFERENCES HORARIO(ID),
    FOREIGN KEY (FK_CLIENTE) REFERENCES CLIENTE(ID)
);

